# Generated by Django 2.2.10 on 2020-06-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop_mail', '0002_auto_20200531_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Ceilings', 'Ceiling Requirements'), ('Skimming', 'Skimming Requirements'), ('Framming', 'Framming Requirements')], default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
