# Generated by Django 2.2.10 on 2020-06-02 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop_mail', '0006_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
